---
title: "Changes in the extent of decline"
output: html_document
editor_options: 
  chunk_output_type: console
---



```{r}
#| eval: true
#| echo: false
#| message: false
library(dplyr)
library(ggplot2)
library(readr)
library(ggforce)
library(DT)
library(purrr)
library(ggpubr)
library(stringr)
#markovchain::markovchainFit(mtz)
library('igraph')
#library(Hmisc)

here::i_am("docs-src/RS/spatial-variability.qmd")
# sessionInfo()
# Suppress summarise info
options(dplyr.summarise.inform = FALSE)
```

```{r}
#| eval: true
#| message: false

source(here::here("inc","R","RS-functions.R"))
source(here::here("inc","R","RS-shared.R"))
target_dir <- "sandbox"
results_file <- here::here(target_dir, "collapse-trajectory-data.rds")
collapse_trajectories <- readRDS(results_file) %>%
  mutate(state=factor(state, state_order))
```

```{r}
pl_data <- collapse_trajectories %>%
  filter(
    countdown>=0, 
    unit_name %in% c("Ruwenzori","Kilimanjaro","Mount Kenia","Puncak Jaya","Sierra Nevada de Santa Marta", "Cordillera de Merida"),
    scenario %in% "SSP2-4.5")

ggplot(pl_data) +
  geom_point(aes(x=countdown,y=RS, colour=state), size=.65) +
  scale_colour_manual(values=state_cat_okabe) +
#  geom_hline(yintercept=c(0.3,0.5,0.8), lty=3, colour="maroon") +
  scale_x_continuous(trans="reverse") +
  xlab("Years before collapse") +
  ylab(expression(bar(RS))) +
  facet_wrap(~unit_name) +
  theme(legend.position="none")

```

```{r}
#| eval: false
from_state <- collapse_trajectories %>% transmute(unit_name,scenario,model_nr,bind_year=year+1,from_state=state)
to_state <- collapse_trajectories %>% transmute(unit_name,scenario,model_nr,bind_year=year,to_state=state)

trans_df <- inner_join(from_state,to_state, by = c("unit_name", "scenario", "model_nr","bind_year"))

adjm1 <- with(trans_df,table(from_state,to_state))
g1<-graph.adjacency(adjm1,weighted=TRUE, mode="undirected",diag = FALSE)
layout <- layout_as_tree(g1, root = 1)
V(g1)$color <- state_cat_okabe[V(g1)$name]
V(g1)$size <- 40 # 3.5*(rowSums(adjm1)/1000)
plot(
  g1, 
  layout = layout, 
  edge.width=(E(g1)$weight / 20),
  vertex.label.color=if_else(V(g1)$name %in% "very local", "black", "white"))

adjm1/rowSums(adjm1)

```

```{mermaid}
%%| label: fig-traj
%%| fig-cap: "Main trajectories towards collapse."
%%| file: states-collapse.mmd
```



----

<details><summary>R session info for this chapter </summary>

```{r}
sessionInfo()
```
</details>