---
title: "T.G.E. Cordilleras de Colombia"
subtitle: "Tropical Glacier Ecosystem of Cordilleras de Colombia"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: load libraries and functions
#| eval: true
#| echo: false
#| message: false
library(dplyr)
library(ggplot2)
library(units)
library(stringr)
library(ggrepel)
library(ggforce)
library(caret)
library(purrr)
library(gbm)
library(readr)
library(ggpubr)
#require(glmmTMB)
#require(lme4)
here::i_am("docs-src/A1/Colombia.qmd")
#sessionInfo()
source(here::here("inc","R","RS-functions.R"))
source(here::here("inc","R","RS-shared.R"))
```

```{r}
#| label: read input data 
#| eval: true
#| message: false
target_dir <- "sandbox"
load(here::here("sandbox","fitted-GBM-models","Cordilleras-de-Colombia.rda")) # this includes slc_unit

rds_file <- here::here(target_dir,"massbalance-totalmass-all-groups.rds")
totalmass_year_data <- readRDS(rds_file) %>%
 filter(unit_name %in% str_replace_all(slc_unit," ","-"))
results_file <- here::here(target_dir, "relative-severity-degradation-suitability-all-tropical-glaciers.csv")
RS_results <- read_csv(results_file, show_col_types = FALSE) %>%
 filter(unit %in% str_replace_all(slc_unit," ","-"))
rds_file <- here::here(target_dir,"relative-severity-degradation-suitability-all-tropical-glaciers-training-thresholds.rds")
RS_results_t <- readRDS(rds_file) %>%
 filter(unit %in% str_replace_all(slc_unit," ","-"))

```



## Compare overall RS 


```{r}

dat1 <- RS_results %>%
  filter(threshold=="ess",  
         modelname == "mri-esm2-0",
         pathway == "ssp126")
dat2 <- dat1 %>% group_by(timeframe) %>%
  summarise(
    n=n(),
    mean_RS=mean(RS_cor,na.rm=T),
    median_RS=median(RS_cor,na.rm=T))

plot_a <- 
  ggplot(dat1) +
    geom_histogram(aes(x=RS_cor*100)) +
    facet_grid(timeframe~.) +
    #scale_fill_brewer(palette = "Oranges",type="seq", direction=-1) +
    #    scale_fill_manual(values = IUCN_cat_colours) +
    #geom_point(data=dat2,aes(x=mean_RS*100, y=15)) +
    #geom_label(data=dat2,aes(x=mean_RS*100, y=15, label=sprintf("mean %0.3f", mean_RS))) +
    #geom_label(data=dat2,aes(x=median_RS*100, y=10, label=sprintf("median %0.3f", median_RS))) +
    theme(legend.position = "none") +
    xlab("Relative severity") +
    ylab("Nr. of cells") 
```

```{r}
tfm <- dat1 %>% distinct(timeframe) %>% pull

fs <- dat1 %>%
  group_by(timeframe) %>%
  group_map(~cED_w(.x$RS)) 

xs <- seq(0,1,length=100)

cEDdata <- bind_rows(
  tibble(timeframe=tfm[1],xs,cED=fs[[1]](xs)),
  tibble(timeframe=tfm[2],xs,cED=fs[[2]](xs)),
  tibble(timeframe=tfm[3],xs,cED=fs[[3]](xs))
)


rss_thr <- c(.80,.50,.30) # IUCN RLE thresholds
#rss_thr <- c(.75,.50,.25) # first second and third quartile

RS_ext_pts <- 
  bind_rows(
    {tibble(rss = rss_thr,timeframe="2011-2040") %>%
      mutate(exts=fs[[1]](rss))},
    {tibble(rss = rss_thr,timeframe="2041-2070") %>%
      mutate(exts=fs[[2]](rss))},
    {tibble(rss = rss_thr,timeframe="2071-2100") %>%
      mutate(exts=fs[[3]](rss))},
    )

plot_b <- 
  ggplot(cEDdata) +
    geom_step(aes(x=xs,y=cED)) +
    facet_col(~timeframe) +
    ylab(expression(ED[RS>=x])) +
    xlab("x") +
    coord_flip(xlim=c(0,1),ylim=c(0,1)) 

```

```{r}

ggarrange(plot_a + coord_flip(), 
          plot_b +  
            geom_vline(xintercept = rss_thr, col = "maroon", lty=3) +
            geom_point(data=RS_ext_pts, aes(y=exts,x=rss), col = "maroon") +
            geom_label(data=RS_ext_pts, 
                      aes(y=exts, x=rss, 
                          label=sprintf("%0.3f",exts)),
                      col = "maroon",
                      cex=3)) 
```


## cED bioclimatic suitability

```{r}
ggplot( cEDdata ) +
  geom_step(aes(x=xs,y=cED,group=timeframe,colour=timeframe)) +
    ylab(expression(ED[RS>=x])) +
    xlab("x") +
    scale_colour_discrete("Future period")

dat1 <- RS_results %>%
  filter(
    threshold=="ess",  
         modelname == "mri-esm2-0",
         pathway == "ssp126"
    ) %>%
  group_by(timeframe) %>%
  group_modify(~summary_cED_w(.x$RS)) 

dat1
```
