---
title: "T.G.E. Mexico"
subtitle: "Tropical Glacier Ecosystem of Mexico"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: load libraries and functions
#| eval: true
#| echo: false
#| message: false
library(dplyr)
library(ggplot2)
library(units)
library(stringr)
library(ggrepel)
library(tidyr)
library(readr)
library(gbm)
library(caret)
#require(glmmTMB)
#require(lme4)
here::i_am("docs-src/A1/Mexico.qmd")
#sessionInfo()
source(here::here("inc","R","RS-functions.R"))
source(here::here("inc","R","RS-shared.R"))
```

```{r}
#| label: read input data 
#| eval: true
#| message: false
target.dir <- "sandbox"

results_file <- here::here(target.dir, "relative-severity-degradation-suitability-all-tropical-glaciers.csv")
RS_results <- read_csv(results_file, show_col_types = FALSE) %>%
  mutate(unit_name=str_replace_all(unit," ","-"))
rds.file <- here::here(target.dir,"totalmass-suitability-glmm-data.rds")
model_data <- readRDS(rds.file)
rds.file <- here::here(target.dir, "massbalance-year-collapse-all-groups.rds")
year_of_collapse_data <- readRDS(rds.file)
load(here::here("sandbox","fitted-GBM-models","Mexico.rda")) # this includes slc_unit

rds.file <- here::here(target.dir,"massbalance-model-data-all-groups.rds")
massbalance_results <- readRDS(rds.file) %>% filter(unit_name %in% slc_unit)
rds.file <- here::here(target.dir,"massbalance-totalmass-all-groups.rds")
totalmass_year_data <- readRDS(rds.file)%>% filter(unit_name %in% slc_unit)
```


## Compare overall RS 


```{r}
mbtdata <- totalmass_year_data %>% 
 filter(
        ssp %in% "SSP5-8.5",
        model_nr %in% " 9"
        ) 

RSdata <- RSts(
  mbtdata$year,
  mbtdata$total_mass,
  formula = "conditional")

mbdata <- massbalance_results %>% 
      filter(
        ssp %in% "SSP5-8.5",
        model_nr %in% " 9"
        )
wgs <- mbdata %>% 
    filter(year == 2000) %>% 
    group_by( RGIId, model_nr) %>% 
    summarise(initial_mass=sum(mass), .groups="keep") 

dat3 <- mbdata %>% 
  group_by(RGIId, model_nr) %>% 
  group_modify(~RSts(.x$year,.x$mass,
                    formula = "conditional")) %>%
  ungroup %>% 
  left_join(wgs, by = c("RGIId", "model_nr"))
  
res <- dat3 %>%
      group_by(year) %>% 
      #group_map(~cED_w(.x$RS,.x$initial_mass))
      group_modify(~summary_cED_w(.x$RS,.x$initial_mass)) %>%
      ungroup 

all_data <- 
  RSdata %>% 
  inner_join(res,by="year") %>% 
  select(year,RS:AUC_cED) 
all_data_pl <- all_data %>%
  pivot_longer( cols=RS:AUC_cED,names_to="summary", values_to="y")

ggplot(all_data_pl) +
  geom_line(aes(x=year,y=y, group=summary,colour=summary)) +
  scale_colour_discrete(type=okabe)


```

```{r}
all_data <- all_data %>% 
  mutate(state=case_when(
    RS == 1 ~ "CO",
    cED_80>=0.80 ~ "CR",
    cED_80>=0.50 ~ "EN",
    cED_50>=0.80 ~ "EN",
    cED_80>=0.30 ~ "VU",
    cED_50>=0.50 ~ "VU",
    cED_30>=0.80 ~ "VU",
    TRUE ~ "LC"
  ))

collapse_year <- all_data %>% filter(state=="CO") %>% summarise(min(year)) %>% pull

all_data <- all_data %>% mutate(countdown= collapse_year - year)

ggplot(all_data %>% filter(countdown>=0)) +
  geom_point(aes(x=countdown,y=RS, colour=state)) +
  scale_colour_manual(values=IUCN_cat_colours) +
  geom_hline(yintercept=c(0.3,0.5,0.8)) +
  scale_x_continuous(trans="reverse") +
  xlab("Years before collapse")



```

## Collapse year: complete loss of ice

```{r}
#| label: fig-Mexico-Ecdf-collapse
#| fig-cap: ECDF (empirical cumulative distribution function) plot of year of collapse for all models (black line) and for each shared socioeconomic pathways (SSP, labeled lines).
#| warning: false


label_xy <- 
  year_of_collapse_data %>% 
  filter(unit_name == slc_unit) %>%
    group_by(ssp) %>% 
  summarise(x=median(collapse_year)) %>%
  mutate(y=0.5)

ggplot(data=year_of_collapse_data %>% 
  filter(unit_name == slc_unit) ) +
#  geom_histogram(aes(x=collapse_year,fill=scn)) +
  stat_ecdf(aes(x=collapse_year,color = ssp,linetype = ssp), 
              geom = "step") +
  stat_ecdf(aes(x=collapse_year), 
              geom = "step",lwd=1.3) +
    geom_label_repel(
    aes(x=x,y=y,label = ssp, color=ssp), data = label_xy,
    size = 3) +
  xlab("Year of collapse") + 
  theme(legend.position = "none")

```

## Bioclimatic suitability model

```{r}
model$finalModel

varImp(model)

plot(model)
```


## Data used in the model


```{r}
rds.file <- here::here(target.dir,"totalmass-suitability-glmm-data.rds")
model_data <- readRDS(rds.file) %>% filter(unit %in% slc_unit)

ggplot(model_data) +
 geom_boxplot(aes(x=time,y=RS,col=method,group=time)) +
 facet_grid(scenario~method)
```