#!/usr/bin/bash

#PBS -l select=2:ncpus=4:mem=60gb
#PBS -l walltime=12:00:00
#PBS -N GBMmodelGlaz
#PBS -k eod
#PBS -j oe
#PBJ -J 2-16

## set up bash environment variables
source $HOME/proyectos/Tropical-Glaciers/T6.1-tropical-glaciers-suitability-model/env/project-env.sh
mkdir -p $GISOUT/$PROJECTNAME/OUTPUT

## load modules for gdal functions
#module purge
module load gdal/3.5.3-szip  r/4.2.2

if [ ! -e $GISOUT/$PROJECTNAME/OUTPUT/current-bioclim-data-all-groups.rda ]
then
    Rscript --vanilla $SCRIPTDIR/inc/R/00-prepare-dataframe.R
fi

Rscript --vanilla $SCRIPTDIR/inc/R/01-gbm-model-fit-and-predict.R ${PBS_ARRAY_INDEX}
Rscript --vanilla $SCRIPTDIR/inc/R/02-gbm-model-predict-future.R ${PBS_ARRAY_INDEX}
