project:
  type: book

book:
  author: "José R. Ferrer-Paris"
  title: "Environmental suitability model for T6.1 tropical glaciers"
  subtitle: "Analysis of future environmental degradation"
  date: "2023-04-03"
  chapters:
    - index.qmd
    - part: "Suitability model"
      chapters:
        - RS-formula.qmd
    - part: "Relative Severity"
      chapters:
        - viz-RS-per-unit.qmd
    - references.qmd
  appendices:
    - general-workflow.qmd
  page-footer:
    left: "Created by: JR Ferrer-Paris"
    right:
      - icon: github
        href: https://github.com/jrfep
      - icon: twitter
        href: https://twitter.com/neomapas
bibliography: 
  - bibtex/references.bib
  - bibtex/glacier-assessments.bib
csl: bibtex/ecological-indicators.csl

execute:
  echo: false

format:
  html:
    theme: cosmo
    number-depth: 2

prefer-html: true
  
  