project:
  type: book

book:
  author: "José R. Ferrer-Paris"
  title: "Environmental degradation and collapse of Tropical Glacier Ecosystems"
  subtitle: "Using relative severity and extent of degradation in collapse risk assessment"
  date: "2023-04-03"
  chapters:
    - index.qmd
    - part: "Assessment units"
      chapters:
        - TGE-units.qmd
    - part: "Indicators of collapse"
      chapters:
        - IND-mass-balance-model.qmd
        - IND-suitability-model.qmd
    - part: "Relative Severity"
      chapters:
        - RS-formula.qmd
        - RS-spatial-aggregation.qmd
        - RS-spatial-variability.qmd
        - RS-time-series.qmd
        - RS-collapse-GLMM.qmd
    - references.qmd
  appendices:
    - A1-general-workflow.qmd
  page-footer:
    left: "Created by: JR Ferrer-Paris"
    right:
      - icon: github
        href: https://github.com/jrfep
      - icon: twitter
        href: https://twitter.com/neomapas
bibliography: 
  - bibtex/references.bib
  - bibtex/glacier-assessments.bib
csl: bibtex/ecological-indicators.csl

execute:
  echo: false

format:
  html:
    theme: cosmo
    number-depth: 2

prefer-html: true
  
  